[server]
# Maximum file upload size in MB
# Setting to very large value to effectively remove limit
# Note: Actual limit may depend on system memory and server configuration
maxUploadSize = 99999

# Enable CORS for development
enableCORS = false

# Enable XSRF protection
enableXsrfProtection = true

[browser]
# Automatically open browser on startup
gatherUsageStats = false
