[server]
# Maximum file upload size in MB
# Setting to very large value to effectively remove limit
# Note: Actual limit may depend on system memory and server configuration
maxUploadSize = 99999

# Bind to localhost only (not accessible from network)
address = "localhost"

# Port number (default: 8501)
port = 8501

# Disable CORS since we're running locally only
enableCORS = false

# Disable XSRF protection for local development
# This is safe since address is bound to localhost only
enableXsrfProtection = false

[browser]
# Automatically open browser on startup
gatherUsageStats = false
